### ISSUE TITLE
How to run this project with clang 14.0.0 ?

### ISSUE THREAD

**Issue by ssantos21** [BlockchainCommons/bc-bip39#30]
I was unable to install clang version 10 using `llvm.sh`.
The error message is:
`E: The repository 'http://apt.llvm.org/jammy llvm-toolchain-jammy-10 Release' does not have a Release file.`

Is there a way to run this project with `clang 14.0.0`, which is the version currently installed with `sudo apt install clang` on Ubuntu 22.04.

**Comment by ssantos21** [comment]
`export CC="clang-14" && ./configure` apparently worked.

**Comment by wolfmcnally** [comment]
Glad to hear you got it working. We're not officially supporting this particular repo any more. If you're trying to do seed backup, I recommend you look into our other initiatives.

**Comment by ChristopherA** [comment]
@ssantos21 As @wolfmcnally said, this repo is not in active use in any of Blockchain Commons projects, so is not a priority to upgrade. But we do review and accept pull requests.

**Comment by ssantos21** [comment]
@ChristopherA @wolfmcnally Thanks for the reply. I'm using this library in a project and it seems to work well and stably. What other initiatives do you recommend instead of this one?

**Comment by wolfmcnally** [comment]
@ssantos21 If you're looking for BIP-39 in particular this is probably fine. For out own BIP-39 compatibility needs we're now using LibWally.
